from functools import lru_cache
from typing import Literal

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "ETF Systematic Portfolio Platform"
    app_env: str = "local"
    api_prefix: str = "/api"
    app_allowed_hosts: str = "localhost,127.0.0.1"
    trust_proxy_headers: bool = False

    postgres_host: str = "localhost"
    postgres_port: int = 5432
    postgres_db: str = "quant_etf"
    postgres_user: str = "quant_etf"
    postgres_password: str = "quant_etf_password"

    redis_host: str = "localhost"
    redis_port: int = 6379
    workflow_execution_mode: Literal["inline", "worker"] = "inline"
    workflow_worker_poll_seconds: float = Field(default=2.0, ge=0.5, le=60)
    workflow_worker_heartbeat_ttl_seconds: int = Field(default=30, ge=5, le=300)
    daily_maintenance_enabled: bool = False
    daily_maintenance_time: str = "18:30"
    daily_maintenance_scope: Literal["core", "positions", "target", "plans", "enabled", "all"] = "enabled"
    daily_maintenance_lookback_days: int = Field(default=10, ge=1, le=365)
    daily_maintenance_max_symbols: int = Field(default=120, ge=1, le=5000)
    daily_maintenance_request_interval_seconds: float = Field(default=1.5, ge=0, le=60)
    daily_maintenance_strategy_code: str = "core_etf_rotation"
    daily_maintenance_portfolio_value: int = Field(default=100000, gt=0)
    daily_maintenance_generate_report: bool = True

    log_level: str = Field(default="INFO")
    tushare_token: str | None = None
    tushare_api_url: str = "https://api.tushare.pro"
    tushare_request_interval_seconds: float = Field(default=1.5)
    deepseek_api_key: str | None = None
    deepseek_base_url: str = "https://api.deepseek.com"
    deepseek_model: str = "deepseek-v4-flash"
    deepseek_timeout_seconds: int = Field(default=45, ge=5, le=180)
    deepseek_max_tokens: int = Field(default=1800, ge=256, le=8000)
    deepseek_thinking_enabled: bool = False

    auth_enabled: bool = False
    auth_admin_username: str = "admin"
    auth_admin_password_hash: str | None = None
    auth_session_secret: str | None = None
    auth_session_ttl_hours: int = Field(default=12, ge=1, le=168)
    auth_cookie_secure: bool = False

    model_config = SettingsConfigDict(
        env_file=(".env", "../.env"),
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    @property
    def database_url(self) -> str:
        return (
            f"postgresql+psycopg://{self.postgres_user}:{self.postgres_password}"
            f"@{self.postgres_host}:{self.postgres_port}/{self.postgres_db}"
        )

    @property
    def redis_url(self) -> str:
        return f"redis://{self.redis_host}:{self.redis_port}/0"

    @property
    def allowed_hosts(self) -> list[str]:
        return [item.strip() for item in self.app_allowed_hosts.split(",") if item.strip()]


def validate_runtime_configuration(settings: Settings) -> None:
    if settings.app_env.lower() != "production":
        return
    errors: list[str] = []
    if not settings.auth_enabled:
        errors.append("AUTH_ENABLED must be true")
    if not settings.auth_admin_password_hash or not settings.auth_admin_password_hash.startswith("pbkdf2_sha256$"):
        errors.append("AUTH_ADMIN_PASSWORD_HASH must be generated by scripts/generate_auth_secrets.py")
    if (
        not settings.auth_session_secret
        or len(settings.auth_session_secret) < 32
        or settings.auth_session_secret.startswith("replace-with-")
    ):
        errors.append("AUTH_SESSION_SECRET must contain at least 32 characters")
    if not settings.auth_cookie_secure:
        errors.append("AUTH_COOKIE_SECURE must be true")
    if settings.postgres_password == "quant_etf_password" or settings.postgres_password.startswith("replace-with-"):
        errors.append("POSTGRES_PASSWORD must not use a default or placeholder value")
    if not settings.allowed_hosts or "*" in settings.allowed_hosts:
        errors.append("APP_ALLOWED_HOSTS must contain explicit host names")
    if not settings.trust_proxy_headers:
        errors.append("TRUST_PROXY_HEADERS must be true behind the production reverse proxy")
    if errors:
        raise RuntimeError("Invalid production configuration: " + "; ".join(errors))


@lru_cache
def get_settings() -> Settings:
    return Settings()
